In [1]:
pip install -U sklearn

Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd
import numpy as np

data = pd.read_csv('breast-cancer-wisconsin.data')
data.columns = ['id', 'clump_thickness', 'uniform_cell_size', 'uniform_cell_shape', 'marginal_adhesion', 'single_epithelial_size', 'bare_nuclei', 'bland_chromatin', 'normal_nucleoli', 'mitoses', 'class']
data['bare_nuclei'] = pd.to_numeric(data['bare_nuclei'], errors='coerce')
data = data.replace(np.nan, 0, regex=True)
data['bare_nuclei'] = data['bare_nuclei'].astype(int)

print(data)

FileNotFoundError: [Errno 2] No such file or directory: 'breast-cancer-wisconsin.data'

In [43]:
#dividimos 
from sklearn.model_selection import train_test_split



X_train, X_test, y_train, y_test = train_test_split(data[['clump_thickness', 'uniform_cell_size', 'uniform_cell_shape', 'marginal_adhesion', 'single_epithelial_size', 'bare_nuclei', 'bland_chromatin', 'normal_nucleoli', 'mitoses']], data['class'], test_size=0.3, random_state=0)


print(X_train)
print('............')
print(X_test)
print('............')
print(y_train)
print('............')
print(y_test)


     clump_thickness  uniform_cell_size  uniform_cell_shape  \
71                 1                  3                   3   
392                1                  1                   1   
406                1                  1                   1   
313                1                  1                   1   
301               10                 10                  10   
..               ...                ...                 ...   
359                6                 10                  10   
192                1                  1                   1   
629                6                  2                   3   
559                5                  1                   1   
684                1                  1                   1   

     marginal_adhesion  single_epithelial_size  bare_nuclei  bland_chromatin  \
71                   2                       2            1                7   
392                  1                       1            1                1   
406

In [42]:
#modelo de vecinos próximos
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing


knn_model = KNeighborsClassifier(n_neighbors=3)
knn_model.fit(X_train, y_train)
y_pred_knn = knn_model.predict(X_test)
print('prediccion de y en modelo de vecinos próximos') 
print(y_pred_knn)

from sklearn.metrics import classification_report, confusion_matrix

print('matriz de confusion')
print(confusion_matrix(y_test, y_pred_knn))

print('reporte de clasificacion')
print(classification_report(y_test, y_pred_knn))

prediccion de y
[4 2 4 4 2 2 2 2 2 2 2 2 2 2 2 2 2 2 4 4 2 4 4 4 2 4 4 4 2 2 4 2 2 2 2 2 2
 4 2 2 2 2 2 4 4 4 2 4 2 4 2 2 2 4 2 2 2 2 2 4 4 4 4 4 2 4 4 2 4 4 2 2 4 2
 2 2 4 2 4 2 4 2 2 2 2 2 4 2 2 4 4 4 2 4 2 4 2 2 2 2 4 4 4 4 2 2 4 2 2 2 2
 4 2 2 4 2 4 2 2 4 2 2 4 4 4 2 2 4 2 2 4 4 2 4 2 2 2 2 4 4 2 2 4 4 2 2 2 4
 2 2 2 4 2 4 2 2 2 2 4 4 4 2 2 2 4 2 2 2 4 2 2 2 2 4 4 2 4 2 2 2 2 2 4 2 4
 2 2 4 4 2 2 4 2 2 2 2 4 4 2 2 2 2 2 2 2 2 4 4 2 2]
matriz de confusion
[[129   4]
 [  3  74]]
reporte de clasificacion
              precision    recall  f1-score   support

           2       0.98      0.97      0.97       133
           4       0.95      0.96      0.95        77

    accuracy                           0.97       210
   macro avg       0.96      0.97      0.96       210
weighted avg       0.97      0.97      0.97       210



In [44]:
#modelo lineal de regesión
from sklearn.linear_model import LogisticRegression

regresion = LogisticRegression()
regresion.fit(X_train, y_train)
y_pred_lineal = regresion.predict(X_test)
print('prediccion de y en modelo lineal de regresión')
print(y_pred_lineal)

from sklearn.metrics import classification_report, confusion_matrix

print('matriz de confusion')
print(confusion_matrix(y_test, y_pred_lineal))

print('reporte de clasificacion')
print(classification_report(y_test, y_pred_lineal))

[4 2 4 4 2 2 4 2 2 2 2 2 2 2 2 2 2 2 4 4 2 4 4 4 2 4 4 4 4 2 4 2 2 2 2 2 2
 4 2 2 2 2 2 4 4 4 2 4 2 4 2 2 2 4 2 2 2 2 2 4 4 2 4 4 2 4 4 2 4 4 2 2 4 2
 2 2 4 2 4 2 4 2 2 2 2 2 4 2 2 4 4 4 2 4 2 4 2 2 2 2 4 4 4 4 2 2 4 2 2 2 2
 4 2 2 2 2 4 2 2 4 2 2 4 4 4 2 2 4 2 2 4 4 2 4 2 2 2 2 4 4 2 2 4 4 2 2 2 4
 2 2 2 4 2 4 2 2 2 2 4 4 4 2 2 2 4 2 2 2 4 2 2 2 2 4 4 2 4 2 2 2 2 2 4 2 4
 2 2 4 4 2 2 4 2 2 2 2 4 4 2 2 2 2 2 2 2 2 4 4 2 2]
[[128   5]
 [  4  73]]
              precision    recall  f1-score   support

           2       0.97      0.96      0.97       133
           4       0.94      0.95      0.94        77

    accuracy                           0.96       210
   macro avg       0.95      0.96      0.95       210
weighted avg       0.96      0.96      0.96       210



In [46]:
#modelo de arbol de decision
from sklearn.tree import DecisionTreeClassifier

arbolDecision = DecisionTreeClassifier()
arbolDecision.fit(X_train, y_train)
y_pred_arbol = arbolDecision.predict(X_test)
print('prediccion de y en modelo de arbol de decision')
print(y_pred_arbol)

from sklearn.metrics import classification_report, confusion_matrix

print('matriz de confusion')
print(confusion_matrix(y_test, y_pred_arbol))

print('reporte de clasificacion')
print(classification_report(y_test, y_pred_arbol))

[4 2 4 4 2 2 4 2 2 2 2 2 2 2 2 2 2 2 4 4 2 4 4 4 2 4 4 4 4 2 4 2 2 2 2 2 2
 4 2 2 2 2 2 4 4 4 2 4 2 4 2 2 2 4 2 2 2 2 2 4 4 4 4 4 2 4 4 2 4 4 2 2 4 2
 2 2 4 2 4 2 4 2 2 2 2 2 4 2 2 4 4 4 2 4 2 4 2 2 2 2 2 4 4 4 2 2 4 2 2 2 4
 4 2 4 4 2 4 2 2 4 2 2 4 4 4 2 2 2 2 2 4 4 2 4 2 2 2 2 4 4 2 2 4 4 2 2 2 4
 2 2 2 4 2 4 4 2 2 2 4 4 4 2 2 2 4 2 2 2 4 2 2 2 2 4 4 2 4 2 2 2 2 2 4 2 4
 2 2 4 4 2 2 4 2 2 2 2 4 4 2 2 2 4 2 2 2 2 4 4 2 2]
[[125   8]
 [  3  74]]
              precision    recall  f1-score   support

           2       0.98      0.94      0.96       133
           4       0.90      0.96      0.93        77

    accuracy                           0.95       210
   macro avg       0.94      0.95      0.94       210
weighted avg       0.95      0.95      0.95       210



In [48]:
#modelo de red neuronal artificial multicapa
from sklearn.neural_network import MLPClassifier
rna = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)
rna.fit(X_train, y_train)
y_pred_rna = rna.predict(X_test)
print('prediccion de y en modelo de red neuronal artificial multicapa')
print(y_pred_rna)

from sklearn.metrics import classification_report, confusion_matrix

print('matriz de confusion')
print(confusion_matrix(y_test, y_pred_rna))

print('reporte de clasificacion')
print(classification_report(y_test, y_pred_rna))

prediccion de y en modelo de red neuronal artificial multicapa
[4 2 4 4 2 2 4 2 2 2 2 2 2 2 2 2 2 2 4 4 2 4 4 4 2 4 4 4 4 2 4 2 2 2 2 2 2
 4 2 2 2 2 2 4 4 4 2 4 2 4 2 2 2 4 2 2 2 2 2 4 4 4 4 4 2 4 4 2 4 4 2 2 4 2
 2 2 4 2 4 2 4 2 2 2 2 2 4 2 2 4 4 4 2 4 2 4 2 2 2 2 4 4 4 4 2 2 4 4 2 2 4
 4 2 2 4 2 4 2 2 4 2 2 4 4 4 2 2 4 2 2 4 4 2 4 2 2 2 2 4 4 4 2 4 4 2 2 2 4
 2 2 2 4 2 4 2 2 2 2 4 4 4 2 2 2 4 2 2 2 4 2 2 2 2 4 4 2 4 2 2 2 2 2 4 2 4
 2 2 4 4 2 2 4 2 2 2 2 4 4 2 2 2 4 2 2 2 2 4 4 2 2]
matriz de confusion
[[126   7]
 [  0  77]]
reporte de clasificacion
              precision    recall  f1-score   support

           2       1.00      0.95      0.97       133
           4       0.92      1.00      0.96        77

    accuracy                           0.97       210
   macro avg       0.96      0.97      0.96       210
weighted avg       0.97      0.97      0.97       210

